-- AlterEnum: Add new values to CancellationCategory
ALTER TYPE "CancellationCategory" ADD VALUE IF NOT EXISTS 'RECIPIENT_UNREACHABLE';
ALTER TYPE "CancellationCategory" ADD VALUE IF NOT EXISTS 'DISTANCE_DISCREPANCY';
ALTER TYPE "CancellationCategory" ADD VALUE IF NOT EXISTS 'ACCIDENTAL_ACCEPT';
ALTER TYPE "CancellationCategory" ADD VALUE IF NOT EXISTS 'ADDRESS_INVALID';
ALTER TYPE "CancellationCategory" ADD VALUE IF NOT EXISTS 'UNDISCLOSED_REQUIREMENTS';
